// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNif2CBiWottXMzOciTPSOQbRck-QIXQ',
    appId: '1:416728721260:web:4f1ad5a1431e1c97497549',
    messagingSenderId: '416728721260',
    projectId: 'chat-app-e30fe',
    authDomain: 'chat-app-e30fe.firebaseapp.com',
    storageBucket: 'chat-app-e30fe.appspot.com',
    measurementId: 'G-X0BS78T16M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJdLp3O4eEBx2bCotqPci8Q8BansMJYLs',
    appId: '1:416728721260:android:c0c1828e76f3d8aa497549',
    messagingSenderId: '416728721260',
    projectId: 'chat-app-e30fe',
    storageBucket: 'chat-app-e30fe.appspot.com',
  );
}
